# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lazysm2 < Formula
  desc "A terminal UI for hmrc/sm2"
  homepage "https://github.com/sunmingdh/lazysm2"
  version "0.1.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sunmingdh/lazysm2/releases/download/v0.1.1/lazysm2_darwin_x86_64.tar.gz"
      sha256 "4ab8ae326e49974c16e9e57ec0159ba67cca951cec3a44b42612a8fad5b17602"

      define_method(:install) do
        bin.install "lazysm2"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sunmingdh/lazysm2/releases/download/v0.1.1/lazysm2_darwin_arm64.tar.gz"
      sha256 "1b02afac80798a9fee2a9d09fa13fd425440fdb54d1378269cd18b749278d2b9"

      define_method(:install) do
        bin.install "lazysm2"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sunmingdh/lazysm2/releases/download/v0.1.1/lazysm2_linux_x86_64.tar.gz"
      sha256 "ecd3ab1a709226552b90516f1950a009668fc5d010266433b5621f85309fbef2"
      define_method(:install) do
        bin.install "lazysm2"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sunmingdh/lazysm2/releases/download/v0.1.1/lazysm2_linux_arm64.tar.gz"
      sha256 "534d811fc1e0b25916562450fdfe6ce963de5b040d1a1b0ecc675981e61d75f3"
      define_method(:install) do
        bin.install "lazysm2"
      end
    end
  end

  def caveats
    <<~EOS
      lazysm2 requires sm2 to be installed and on your PATH.
    EOS
  end
end
